---
version: "3.8"
volumes:
  docker-volume:
services:
  db:
    image: mysql:5.7
    container_name: mysqld
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - docker-volume:/var/lib/mysql
